default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: FilmArchive_development

test:
  <<: *default
  database: FilmArchive_test

production:
  <<: *default
  database: FilmArchive_production
  username: FilmArchive
  password: <%= ENV['FILMARCHIVE_DATABASE_PASSWORD'] %>
